---
- name: Playbook to view EEM script
  hosts: cisco_ios
  gather_facts: no
  connection: network_cli

  tasks:

  - name: Checking EEM script configuration
    ios_command:
       commands:
        - sh event manager policy registered
    register: output
    
  - debug:
      var: output.stdout

